'use client'
import { useState,createContext } from 'react';
import 'bootstrap/dist/css/bootstrap.min.css'
import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'

import { useContext } from "react";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const ThemeContext = createContext({})

export default function RootLayout({ children }) {

  const [selectedSc,setSelectedSc] = useState()
  const [darkTheme, setDarkTheme] = useState(false);

  const cambiarDarkTheme = () => setDarkTheme(!darkTheme);

  return (
    <html lang="en">
      <ThemeContext.Provider value={{darkTheme,cambiarDarkTheme}}>
      <body className={darkTheme?"bg-secondary":"bg-secondary-subtle"}>
        <nav className="navbar fixed-top navbar-expand-lg bg-body-secondary" data-bs-theme={darkTheme?"dark":""}>
              <div className="container-fluid">
                  <Link href="/" className="navbar-brand d-flex  align-items-center">
                      <img src="/img/logo.png" alt="Logo" height="35" className="d-inline-block align-text-top"/>
                      <span className="fs-2 ps-3 fw-bold">ElecScoot</span>
                  </Link>
                  <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span className="navbar-toggler-icon"></span>
                  </button>
                  <div className="collapse navbar-collapse" id="navbarNav">
                    <ul className="navbar-nav">
                      <li className="nav-item">
                        <Link href="/" className="nav-link active">Home</Link>
                      </li>
                      <li className="nav-item">
                        <Link href="/scooter" className="nav-link">Scooters</Link>
                      </li>
                      <li className="nav-item">
                        <Link href="/marcas" className="nav-link">Marcas</Link>
                      </li>
                      <li className="nav-item">
                        <Link href="/nuevos" className="nav-link">Nuevos</Link>
                      </li>
                    </ul>
                  </div>
                  <div className="form-check form-switch">
                      <input className="form-check-input" 
                      type="checkbox" role="switch" 
                      onChange={()=>{cambiarDarkTheme();}}
                      id="flexSwitchCheckDefault" />
                      <label className={darkTheme?"form-check-label text-light":"form-check-label"} htmlFor="flexSwitchCheckDefault">Tema oscuro</label>
                  </div>
              </div>
          </nav>
          {children}
      </body>
      </ThemeContext.Provider>
    </html>
  )
}
